<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MXR.SDK.Protocol.Tests</RootNamespace>
    <AssemblyName>MXR.SDK.Protocol.Tests</AssemblyName>
    <EnableDefaultItems>false</EnableDefaultItems>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/MXR.SDK/Tests/Protocol/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MXR.SDK.Protocol/MXR.SDK.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>
</Project>
